### ISSUE TITLE
No option to close websockets / stop polling

### ISSUE THREAD

**Issue by cdevalence** [rjsamson/stockfighter#16]
I may be missing something (new to Ruby/Rails/Websockets), but there doesn't appear to be any way to close any of the websockets once you start them. Similarly the GM polling doesn't provide any way to stop polling if e.g. the level is completed. Are there design/convention reasons not to do this?

**Comment by pleschev** [comment]
G'day!

I've avoided adding cleanup / stopping code as I use the following callback that stopping the process as soon as there's a win or a loss:

```
            gm.add_state_change_callback { |previous_state, new_state|
                if new_state == 'won'
                    abort('all done - won!')
                end

                if new_state == 'lost'
                    abort('all done - lost!')
                end
            }
```

**Comment by rjsamson** [comment]
I think what @pleschev said covers it!

**Comment by cdevalence** [comment]
Great, thanks. Is there a similar way to get the GM to stop polling? I tried putting it in a separate thread and then killing the thread, but as per scheduler documentation it just starts a new thread for the scheduled job (every 10 seconds poll the API).

**Comment by rjsamson** [comment]
@cdevalence are you just not wanting to use polling you mean? You can always just start the GM without polling: true.

**Comment by cdevalence** [comment]
No, I'd like to start the GM with polling: true, do things during the level, and be notified of a win/loss so I can abort the level and move on to the next one... But aborting the level doesn't stop the polling so I'm trying to figure out how to clean that up as it seems like a bad idea to have all these polls staying open indefinitely as I re-run the level or start the next level.

**Comment by pleschev** [comment]
> Great, thanks. Is there a similar way to get the GM to stop polling?

Using the same approach (the callback above) will kill the process, and thus stop the polling of the GM thread / rufus scheduler

**Comment by cdevalence** [comment]
Sorry, I'm pretty sure I'm missing something here. Which process will be killed that stops the GM / rufus polling?

Edit: Are you running each instance of a level in its own process?
