### ISSUE TITLE
Websocket connections fail with 1002 after a period of time

### ISSUE THREAD

**Issue by pleschev** [rjsamson/stockfighter#6]
``` ruby
/stockfighter/lib/stockfighter/websockets.rb:58:in `block (2 levels) in start': tickertape websocket: Client disconnected with status code: 1002 and reason:  (RuntimeError)
    from /usr/local/lib/ruby/gems/2.1.0/gems/websocket-eventmachine-base-1.1.1/lib/websocket/eventmachine/base.rb:152:in `call'
    from /usr/local/lib/ruby/gems/2.1.0/gems/websocket-eventmachine-base-1.1.1/lib/websocket/eventmachine/base.rb:152:in `block (2 levels) in <class:Base>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/websocket-eventmachine-base-1.1.1/lib/websocket/eventmachine/base.rb:125:in `unbind'
    from /usr/local/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1465:in `event_callback'
    from /usr/local/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:202:in `release_machine'
    from /usr/local/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:202:in `run'
```

which according to https://github.com/igrigorik/em-websocket relates to a WebSocket protocol error.

**Comment by rjsamson** [comment]
After how long does this occur? Did you see my comments in slack about [faye/websocket](https://github.com/faye/faye-websocket-ruby)? That's what I used to websockets through all levels, including leaving them open for a long time, and did not experience any issues.

**Comment by pleschev** [comment]
It's totally random, looking into the code it could mean a whole range of situations

It could be related to how my callbacks are written as well. I was going to swap in the faye/websocket impel and then it started working for 45+mins without any problems

It also happened when the exchange became unresponsive 

Not going to close this issue until I get it working reliably :)

**Comment by pleschev** [comment]
Ok, i strongly suspect that most of the problems are related to how I've written my callbacks. I have since discovered that eventmachine calls everything on the 1 thread & I was making api place_orders on that thread, delaying the processing of the subsequent messages coming through. At a minimum, I'll add extra documentation mentioning the need to wrap long operations within your callbacks with EM.defer

**Comment by pleschev** [comment]
PR #10 fixes this

**Comment by rjsamson** [comment]
PR #10 is merged in, so I think this is good to close.
